### ISSUE TITLE
gds fails on resizer_timing.tcl on tt01 resubmission for tt02 file

### ISSUE THREAD

**Issue by youngpines** [TinyTapeout/tt02-submission-template#23]
Link to wokwi -> https://wokwi.com/projects/341571228858843732

This project was submitted for tt01 and was resubmitted for tt02. Please let me know if I should provide additional information or post this issue somewhere else. gds fails with the following error
```
###############################################################################
# Design Rules
###############################################################################
set_max_fanout 5.0000 [current_design]
[INFO]: Setting RC values...
[INFO RSZ-0046] Found 1 endpoints with hold violations.
[WARNING RSZ-0064] Unable to repair all hold checks within margin.
[INFO RSZ-0032] Inserted 254 hold buffers.
[ERROR RSZ-0060] Max buffer count reached.
Error: resizer_timing.tcl, 62 RSZ-0060
Error: : during executing openroad script /openlane/scripts/openroad/resizer_timing.tcl
Error: : Exit code: 1
Error: : full log: ../work/runs/wokwi/logs/cts/13-resizer.log
Error: : Last 10 lines:
child process exited abnormally
```

**Comment by mattvenn** [comment]
I opened an issue here: https://github.com/The-OpenROAD-Project/OpenLane/issues/1515
It's happening because I enabled clock tree synthesis. 
You might be able to resolve it by avoiding using pin0 as your design shouldn't need a clock tree.
If I delete pin0 connection to the and, and just join the and pins together, I don't get the error.

**Comment by mattvenn** [comment]
Hi,

The issue comes from me enabling clock tree synthesis on TT02.

I don't know why your design fails, it should be straightforward to route, so I opened an issue here: https://github.com/The-OpenROAD-Project/OpenLane/issues/1515

For now, I'd suggest avoiding pin0 as a clock. This _should_ work because your design is so small it doesn't need a clock tree.

**Comment by youngpines** [comment]
@mattvenn I've removed the AND gate and fanned out the clock from pin0 instead. It passes gds, and I've submitted this design. 
Thanks for the insight and help! Should this issue be closed since the design is submitted?

**Comment by mattvenn** [comment]
thanks! good to have you on tt02!
